### PR TITLE
ARQ-2191 Arquillian tomcat managed container does not work on JDK9

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Awesome! Thank you very much @zhfeng for this contribution. Could you add `oraclejdk9` to `.travis.yml` as part of this PR so we can see tests passing?

**Comment by zhfeng** [comment]
@bartoszmajsak I added it.

**Comment by zhfeng** [comment]
```
[ERROR] Source option 1.5 is no longer supported. Use 1.6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
```
It looks like JDK9 does not support this and we have to upgrade to 1.6 ?

**Comment by zhfeng** [comment]
@bartoszmajsak the tests pass on the jdk9 and do you think it is OK to merge ?

**Comment by bartoszmajsak** [comment]
Thanks @zhfeng. Bumping to `1.6` bytecode should be fine.

**Pull request merged**
