### PR TITLE
ARQ-2033 Fixed the Tomcat launch command line generation to use the local file…

### PR DESCRIPTION
**Pull request by cableDave**
… system path convention instead of hard coded '/' characters in string fragments.

This allows for Managed Tomcat testing for developers afflicted by Windows

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Thanks a lot for this contribution. Could you fix formatting? I will take care of bringing it upstream tonight.

**Comment by cableDave** [comment]
Need to see about importing the format settings & recommit the branch - have to see if the 'inspections.xml' file is compatible with current Idea release

**Comment by bartoszmajsak** [comment]
It's only about the spaces. You can simply commit to the same branch on your fork. No need to closing the PR.

**Comment by MatousJobanek** [comment]
Landed in https://github.com/arquillian/arquillian-container-tomcat/commit/2ad2d38275268723d25d97497c1b88f222a59a0a :rocket: Thanks :+1: 
I'm sorry about the delay

**Pull request closed without merging**
