### PR TITLE
Allow automatic port selection by tomcat

### PR DESCRIPTION
**Pull request by pschwarzer-tt**
#### Short description of what this resolves:
As discussed in here: https://github.com/arquillian/arquillian-container-tomcat/issues/115 here the pull request to allow automatic port selection by the arquillian tomcat plugin.

I added comments to all done changes.

#### Changes proposed in this pull request:

- allow automatic port selection by Tomcat class

**Fixes**: #

- changed final HTTPContext httpContext = new HTTPContext(configuration.getBindAddress(), configuration.getBindHttpPort()); to new HTTPContext(tomcat.getHost().getName(), tomcat.getConnector().getLocalPort()); in Tomcat8EmbeddedContainer.java so HTTPContext uses port choosen by Tomcat, and no longer set by user in configuration. This allows setting of 0 and to let tomcat choose an available port by its own.

- changed ((StandardHost) host).setUnpackWARs(configuration.isUnpackArchive()); back to embeddedHostConfig.setUnpackWARs(configuration.isUnpackArchive()); because in out arquillian setup, ((StandardHost) host).setUnpackWARs(configuration.isUnpackArchive());  will not work propably

### CODE REVIEW

**Comment by rhusar** [comment]
Hi @pschwarzer-tt, any chance you are still active and could rebase the change?

**Comment by jansohn** [comment]
> Hi @pschwarzer-tt, any chance you are still active and could rebase the change?

After looking at his profile I doubt he is still active. Can you rebase it yourself or should I open a new PR? I'm also interested in this feature / fix.

**Comment by rhusar** [comment]
> > Hi @pschwarzer-tt, any chance you are still active and could rebase the change?
> 
> After looking at his profile I doubt he is still active. Can you rebase it yourself or should I open a new PR? I'm also interested in this feature / fix.

I am afraid so :-(

This needs more work and testing than just simple rebase, I can have a look next week at the earliest. You can take a stab if you want.

**Comment by pschwarzer-tt** [comment]
Hi, its to long ago, not working with this anymore. Can someone else take over?

**Comment by rhusar** [comment]
> Hi, its to long ago, not working with this anymore. Can someone else take over?

Thanks @pschwarzer-tt ! @jansohn has - https://github.com/arquillian/arquillian-container-tomcat/pull/179

Closing!

**Pull request closed without merging**
